---
version: '3.7'

services:
  loja-frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    ports:
      - '3000:3000'
  loja-backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    ports:
      - '8000:8000'
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'