---
version: '3.7'

services:
  loja-frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    ports:
      - '3000:3000'
  # atlax-backend:
  #   build:
  #     context: ..
  #     dockerfile: backend.Dockerfile
  #   ports:
  #     - '8000:8000'